-- 业务用户表
CREATE TABLE biz_user (
  id INT NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  username VARCHAR(50) NOT NULL COMMENT '用户名',
  password VARCHAR(255) NOT NULL COMMENT '密码',
  slat VARCHAR(255) NOT NULL COMMENT '盐值',
  session_id VARCHAR(255) DEFAULT NULL COMMENT '会话ID',
  nickname VARCHAR(50) DEFAULT NULL COMMENT '昵称',
  avatar VARCHAR(255) DEFAULT NULL COMMENT '头像',
  mobile VARCHAR(20) NOT NULL COMMENT '手机号',
  email VARCHAR(100) NOT NULL COMMENT '邮箱',
  status TINYINT DEFAULT 1 COMMENT '状态（0:禁用 1:启用）',
  last_login_time DATETIME DEFAULT NULL COMMENT '最后登录时间',
  last_login_ip VARCHAR(20) DEFAULT NULL COMMENT '最后登录IP',
  created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT(4) DEFAULT 0 COMMENT '逻辑删除标记',
  PRIMARY KEY (id),
  UNIQUE KEY biz_user_unique_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci COMMENT='业务用户表';;


id INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
username VARCHAR(50) NOT NULL COMMENT '用户名',
nickname VARCHAR(50) DEFAULT NULL COMMENT '昵称',
status TINYINT DEFAULT 1 COMMENT '状态',
created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
PRIMARY KEY (`user_id`,`role_id`),
UNIQUE KEY `biz_user_unique_mobile` (`mobile`),
INDEX `biz_user_idx_ctime` (`created_time`)