<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.7.0</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

	<groupId>cc.abing</groupId>
	<artifactId>abstart-parent</artifactId>
	<version>${revision}</version>
	<name>ABStart</name>
	<description>A Simple Spring Boot Project</description>
	<packaging>pom</packaging>


	<properties>
		<!--版本号-->
		<revision>0.0.1-SNAPSHOT</revision>
	</properties>

	<modules>
		<module>api</module>
		<module>biz</module>
		<module>dao</module>
		<module>model</module>
		<module>util</module>
		<module>support</module>
	</modules>

	<dependencyManagement>
		<dependencies>
			<!--子模块-START-->
			<dependency>
				<groupId>cc.abing</groupId>
				<artifactId>abstart-api</artifactId>
				<version>${revision}</version>
			</dependency>
			<dependency>
				<groupId>cc.abing</groupId>
				<artifactId>abstart-biz</artifactId>
				<version>${revision}</version>
			</dependency>
			<dependency>
				<groupId>cc.abing</groupId>
				<artifactId>abstart-dao</artifactId>
				<version>${revision}</version>
			</dependency>
			<dependency>
				<groupId>cc.abing</groupId>
				<artifactId>abstart-model</artifactId>
				<version>${revision}</version>
			</dependency>
			<dependency>
				<groupId>cc.abing</groupId>
				<artifactId>abstart-support</artifactId>
				<version>${revision}</version>
			</dependency>
			<dependency>
				<groupId>cc.abing</groupId>
				<artifactId>abstart-util</artifactId>
				<version>${revision}</version>
			</dependency>
			<!--子模块-END-->

			<!--全局排除logback,使用log4j2日志框架-->
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-logging</artifactId>
				<exclusions>
					<exclusion>
						<groupId>*</groupId>
						<artifactId>*</artifactId>
					</exclusion>
				</exclusions>
			</dependency>

			<!-- 三方库-START-->
			<dependency>
				<groupId>p6spy</groupId>
				<artifactId>p6spy</artifactId>
				<version>3.9.1</version>
			</dependency>
			<dependency>
				<groupId>com.baomidou</groupId>
				<artifactId>mybatis-plus-boot-starter</artifactId>
				<version>3.5.1</version>
			</dependency>
			<dependency>
				<groupId>com.baomidou</groupId>
				<artifactId>mybatis-plus-annotation</artifactId>
				<version>3.5.1</version>
			</dependency>
			<dependency>
				<groupId>com.baomidou</groupId>
				<artifactId>mybatis-plus-generator</artifactId>
				<version>3.5.2</version>
			</dependency>
			<!--多数据源支持-->
			<dependency>
				<groupId>com.baomidou</groupId>
				<artifactId>dynamic-datasource-spring-boot-starter</artifactId>
				<version>3.2.1</version>
			</dependency>
			<dependency>
				<groupId>org.freemarker</groupId>
				<artifactId>freemarker</artifactId>
				<version>2.3.31</version>
			</dependency>
			<dependency>
				<groupId>com.fasterxml.jackson.core</groupId>
				<artifactId>jackson-annotations</artifactId>
				<version>2.13.3</version>
			</dependency>
			<!--mapstruct核心-->
			<dependency>
				<groupId>org.mapstruct</groupId>
				<artifactId>mapstruct</artifactId>
				<version>1.5.2.Final</version>
			</dependency>
			<!--mapstruct编译-->
			<dependency>
				<groupId>org.mapstruct</groupId>
				<artifactId>mapstruct-processor</artifactId>
				<version>1.5.2.Final</version>
			</dependency>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-lang3</artifactId>
				<version>3.9</version>
			</dependency>
			<dependency>
				<groupId>com.google.guava</groupId>
				<artifactId>guava</artifactId>
				<version>31.1-jre</version>
			</dependency>
			<!-- 三方库-END-->
		</dependencies>
	</dependencyManagement>




	<build>
		<plugins>
			<plugin>
				<groupId>io.spring.javaformat</groupId>
				<artifactId>spring-javaformat-maven-plugin</artifactId>
				<version>0.0.35</version>
				<executions>
					<execution>
						<phase>validate</phase>
						<inherited>true</inherited>
						<configuration>
							<skip>false</skip>
						</configuration>
						<goals>
							<goal>validate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
<!--            <plugin>-->
<!--                <groupId>org.apache.maven.plugins</groupId>-->
<!--                <artifactId>maven-checkstyle-plugin</artifactId>-->
<!--                <version>3.1.1</version>-->
<!--                <dependencies>-->
<!--                    <dependency>-->
<!--                        <groupId>com.puppycrawl.tools</groupId>-->
<!--                        <artifactId>checkstyle</artifactId>-->
<!--                        <version>9.3</version>-->
<!--                    </dependency>-->
<!--                    <dependency>-->
<!--                        <groupId>io.spring.javaformat</groupId>-->
<!--                        <artifactId>spring-javaformat-checkstyle</artifactId>-->
<!--                        <version>0.0.35</version>-->
<!--                    </dependency>-->
<!--                </dependencies>-->
<!--                <executions>-->
<!--                    <execution>-->
<!--                        <id>checkstyle-validation</id>-->
<!--                        <phase>validate</phase>-->
<!--                        <inherited>true</inherited>-->
<!--                        <configuration>-->
<!--                            <configLocation>io/spring/javaformat/checkstyle/checkstyle.xml</configLocation>-->
<!--                            <includeTestSourceDirectory>true</includeTestSourceDirectory>-->
<!--                        </configuration>-->
<!--                        <goals>-->
<!--                            <goal>check</goal>-->
<!--                        </goals>-->
<!--                    </execution>-->
<!--                </executions>-->
<!--            </plugin>-->
		</plugins>
	</build>


</project>
