spring.profiles.active= default
spring.application.name = abstart
server.port=12345
server.address=127.0.0.1

spring.datasource.dynamic.primary=mariadb
spring.datasource.dynamic.strict=false
spring.datasource.dynamic.datasource.mariadb.url=jdbc:mysql://localhost:3306/abstart
spring.datasource.dynamic.datasource.mariadb.username=root
spring.datasource.dynamic.datasource.mariadb.password=
spring.datasource.dynamic.datasource.mariadb.driver-class-name=com.mysql.cj.jdbc.Driver
