spring.profiles.active= local

spring.application.name = ABStart
server.port=12345
server.address=127.0.0.1

spring.jackson.time-zone = GMT+8
spring.jackson.date-format = yyyy-MM-dd HH:mm:ss
spring.jackson.property-naming-strategy = SNAKE_CASE
spring.jackson.default-property-inclusion = NON_NULL
#spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=true
spring.jackson.serialization.WRITE-ENUMS-USING-INDEX=false
spring.jackson.serialization.WRITE-ENUMS-USING-TO-STRING=true

mybatis-plus.global-config.db-config.id-type= AUTO

spring.datasource.dynamic.primary=mysql
spring.datasource.dynamic.strict=false
spring.datasource.dynamic.p6spy = true
spring.datasource.dynamic.hikari.pool-name = HikariCP
spring.datasource.dynamic.hikari.min-idle = 5
spring.datasource.dynamic.hikari.idle-timeout = 30000
spring.datasource.dynamic.hikari.max-pool-size = 20
spring.datasource.dynamic.hikari.max-lifetime = 900000
spring.datasource.dynamic.hikari.is-auto-commit = true
spring.datasource.dynamic.hikari.connection-timeout = 5000
spring.datasource.dynamic.hikari.connection-test-query = SELECT 1